export  const FIELD_LIST = [
  {
    "Name": "Все",
    "Id": -1,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "поле1",
    "Id": 12,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "поле2",
    "Id": 14,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "поле3",
    "Id": 15,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "поле4",
    "Id": 16,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "поле5",
    "Id": 17,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "поле6",
    "Id": 18,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "поле7",
    "Id": 19,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  }
];

export const ORG_LIST = [
  {
    "Name": "Все",
    "Id": -1,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "ООО ЦПИ \"ПРИС\"",
    "Id": 1,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  }
];

export const PLANTS_LIST = [
  {
    "Name": "Все",
    "Id": -1,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Абрикос",
    "Id": 23,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Алыча",
    "Id": 33,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Вишня",
    "Id": 31,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Выведенный участок",
    "Id": 26,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Горох",
    "Id": 11,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Гречиха",
    "Id": 41,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Груша",
    "Id": 39,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "День поля",
    "Id": 25,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Земляника",
    "Id": 9,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Зерносмесь на сено (ячмень+горох)",
    "Id": 40,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Капуста",
    "Id": 8,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Картофель",
    "Id": 20,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "картофель семенной",
    "Id": 44,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Косточковые",
    "Id": 24,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Кукуруза",
    "Id": 4,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Кукуруза на силос",
    "Id": 37,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Луговое сено",
    "Id": 30,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Лук",
    "Id": 5,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Малина",
    "Id": 15,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "МКРС",
    "Id": 28,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Многолетние травы",
    "Id": 21,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Морковь",
    "Id": 13,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "огурец",
    "Id": 47,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Однолетние травы",
    "Id": 43,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Озимая пшеница",
    "Id": 6,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Пар",
    "Id": 7,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Подсолнечник",
    "Id": 3,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Показательный участок",
    "Id": 45,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Сахарная свекла",
    "Id": 14,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Сахарная свекла полив",
    "Id": 42,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Семена сах.свеклы на штеклинги",
    "Id": 48,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Сенаж",
    "Id": 27,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Слива",
    "Id": 32,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Солома пшеничная",
    "Id": 35,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Солома ячменная",
    "Id": 34,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Соя",
    "Id": 16,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Соя (на давальческих условиях)",
    "Id": 46,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Ст. свекла",
    "Id": 22,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Тыква",
    "Id": 49,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Урожай",
    "Id": 36,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Цикорий",
    "Id": 18,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Штеклинги",
    "Id": 10,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Яблоневый сад",
    "Id": 17,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Яровая пшеница",
    "Id": 2,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "Ячмень",
    "Id": 1,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  }
];

export const YEARS_LIST = [
  {
    "Name": "2000",
    "Id": 2000,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2001",
    "Id": 2001,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2002",
    "Id": 2002,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2003",
    "Id": 2003,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2004",
    "Id": 2004,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2005",
    "Id": 2005,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2006",
    "Id": 2006,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2007",
    "Id": 2007,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2008",
    "Id": 2008,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2009",
    "Id": 2009,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2010",
    "Id": 2010,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2011",
    "Id": 2011,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2012",
    "Id": 2012,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2013",
    "Id": 2013,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2014",
    "Id": 2014,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2015",
    "Id": 2015,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2016",
    "Id": 2016,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2017",
    "Id": 2017,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2018",
    "Id": 2018,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2019",
    "Id": 2019,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2020",
    "Id": 2020,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2021",
    "Id": 2021,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2022",
    "Id": 2022,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2023",
    "Id": 2023,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2024",
    "Id": 2024,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2025",
    "Id": 2025,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2026",
    "Id": 2026,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2027",
    "Id": 2027,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2028",
    "Id": 2028,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2029",
    "Id": 2029,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2030",
    "Id": 2030,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2031",
    "Id": 2031,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2032",
    "Id": 2032,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2033",
    "Id": 2033,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2034",
    "Id": 2034,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2035",
    "Id": 2035,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2036",
    "Id": 2036,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2037",
    "Id": 2037,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2038",
    "Id": 2038,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2039",
    "Id": 2039,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2040",
    "Id": 2040,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2041",
    "Id": 2041,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2042",
    "Id": 2042,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2043",
    "Id": 2043,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2044",
    "Id": 2044,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2045",
    "Id": 2045,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2046",
    "Id": 2046,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2047",
    "Id": 2047,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2048",
    "Id": 2048,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2049",
    "Id": 2049,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2050",
    "Id": 2050,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  },
  {
    "Name": "2051",
    "Id": 2051,
    "Bold": null,
    "Price": null,
    "Balance": null,
    "Current_price": null,
    "Description": null,
    "Manufacturer": null,
    "Area_plant": 0,
    "Area": 0,
    "index": null,
    "emp_emp_id": null,
    "RepairStatus": null
  }
];


